apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-shop
  labels:
    app: fake-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      labels:
        app: fake-shop
    spec:
      containers:
        - name: fake-shop
          image: fabricioveronez/fake-shop:latest
          ports:
            - containerPort: 5000
          env:
          - name: DB_HOST 
            value: postgres.default.svc.cluster.local
          - name: DB_USER 
            valueFrom:
              secretKeyRef:
                name: fake-shop-secret
                key: db-user
          - name: DB_PASSWORD  
            valueFrom:
              secretKeyRef:
                name: fake-shop-secret
                key: db-password
          - name: DB_NAME  
            valueFrom:
              secretKeyRef:
                name: fake-shop-secret
                key: db-name
          - name: DB_PORT
            value: '5432'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: fake-shop-secret
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fake-shop-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fake-shop-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: fake-shop-secret
type: Opaque
data:
  db-host: bG9jYWxob3N0
  db-port: NTQzMg==
  db-name: ZWNvbW1lcmNl
  db-user: ZWNvbW1lcmNl
  db-password: UGcxMjM0